# Generated by Django 5.0.7 on 2024-08-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro_vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="activo",
            field=models.BooleanField(default=False),
        ),
    ]
